sudo: required

services:
  - docker

before_install:
  - docker build -t petrepatrasc/docker-php-fpm-development .

script:
  - docker run -d petrepatrasc/docker-php-fpm-development

after_script:
  - docker kill $(docker ps -q)
  - docker rm $(docker ps -aq)
  - docker rmi $(docker images -q)
