sudo: true

services:
  - docker

before_install:
  - docker build -t petrepatrasc/docker-php-fpm-development .

script:
  - docker run -d --name php_dev petrepatrasc/docker-php-fpm-development

after_script:
  - sudo docker kill $(docker ps -q);
  - sudo docker rm $(docker ps -aq);
  - sudo docker rmi $(docker images -q);
