sudo: true

services:
  - docker

before_install:
  - ./test/start-test-container.sh

script:
  - ./test/run-tests.sh

after_script:
  - sudo docker kill $(docker ps -q);
  - sudo docker rm $(docker ps -aq);
  - sudo docker rmi $(docker images -q);
