sudo: required

services:
  - docker

before_install:
  - ./test/start-test-container.sh

script:
  - ./test/run-tests.sh

after_script:
  - docker kill $(docker ps -q);
  - docker rm $(docker ps -aq);
  - docker rmi $(docker images -q);
